[package]
name = "leantest"
version = "0.1"
lean_version = "leanprover-community/lean:3.16.5"
path = "src"

[dependencies]
mathlib = {git = "https://github.com/leanprover/mathlib", rev = "2d270ff1bfc16a26624297850501eb284b2eeaf3"}
